### ISSUE TITLE
CraftDisable is returning null.

### ISSUE THREAD

**Issue by benrobson8** [benrobson8/zander#133]

**Comment by benrobson8** [comment]
```
[13:34:40] [Server thread/ERROR]: Could not pass event PrepareItemCraftEvent to zander v1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1094) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.ContainerWorkbench.a(ContainerWorkbench.java:70) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.ContainerWorkbench.lambda$0(ContainerWorkbench.java:80) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.ContainerAccess.lambda$0(ContainerAccess.java:59) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.ContainerAccess$2.a(ContainerAccess.java:46) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.ContainerAccess.a(ContainerAccess.java:58) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.ContainerWorkbench.a(ContainerWorkbench.java:79) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.InventoryCrafting.setItem(InventoryCrafting.java:135) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.Slot.set(SourceFile:80) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.Container.a(Container.java:334) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2141) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at com.shadowolfyt.zander.events.CraftDisable.CraftDisable(CraftDisable.java:22) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        ... 27 more
```
